name: SparkEnv
dependencies:
  - python=3.8
  - numpy=1.21.*
  - pip:
    - toml
    - pyspark
    - boto3
    - kafka-python
    - confluent-kafka
    - avro-python3
    - pandas
    - requests
    