piVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fractal-kafka-cluster
spec:
 
  kafka:
    version: 3.2.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
    
    
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic-1
  labels:
    strimzi.io/cluster: fractal-kafka-cluster
spec:
  replicas: 3
  partitions: 5

---
apiVersion: v1

kind: Service

metadata:

  name: fractal-schema-registry-service

spec:

  type: LoadBalancer

  selector:

    app: cp-schema-registry

    release: kafka-schema-registry

  ports:

  - protocol: TCP

    port: 8081

    targetPort: 8081    

---
apiVersion: v1

kind: Service

metadata:

  name:   fractal-ksql-server

spec:

  type: LoadBalancer

  selector:

     app: cp-ksql-server
     release: ksql-server
  ports:

  - protocol: TCP

    port: 8088

    targetPort: 8088     
