apiVersion: v1
kind: Service
metadata:
  name:   fractal-ksql-server
spec:
  type: LoadBalancer
  selector:
     app: cp-ksql-server
     release: ksql-server
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088    