apiVersion: v1
kind: Service
metadata:
  name: fractal-schema-registry-service
spec:
  type: LoadBalancer
  selector:
    app: cp-schema-registry
    release: kafka-schema-registry
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
